apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
 
spec:
  selector:
    matchLabels:
      app: mysql
 
  template:
    metadata:
      labels:
        app: mysql
 
    spec:
      containers:
        - name: database-container
          image: 494992235231.dkr.ecr.us-east-1.amazonaws.com/database-image-docker-assignment:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
 
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: database-pvc