apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: database-container
          image: .dkr.ecr.us-east-1.amazonaws.com/database-image-docker-assignment:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: MYSQL_DATABASE         
            
          # env:
          #   - name: MYSQL_ROOT_PASSWORD
          #     value: password1234
          #   - name: MYSQL_DATABASE
          #     value: employees
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data