apiVersion: v1
kind: Service
metadata:
  name: appNodeservice
  labels:
    app: employees
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 81
    nodePort: 30000
  selector:
    app: employees